image: node:8.11-jessie
cache:
  paths:
    - node_modules/

stages:
  - lint
  - test
  - deploy

ESlint:
  stage: lint
  before_script:
    - yarn install
  script:
    - yarn lint

Test 6:
  stage: test
  image: node:6
  before_script:
    - yarn install
  script:
    - yarn test

Test 8:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test

Deploy:
  stage: deploy
  before_script:
    - yarn install
  script:
    - yarn deploy




